; This file was auto-generated by drush make
core = 7.x

api = 2
;Download drupal core
projects[] = drupal

; Modules
projects[] = advanced_help
projects[advanced_help][subdir] = contrib
projects[] = context
projects[context][subdir] = contrib
projects[] = ctools
projects[ctools][subdir] = contrib
projects[] = entity
projects[entity][subdir] = contrib
projects[] = features
projects[features][subdir] = contrib
projects[] = jquery_update
projects[jquery_update][subdir] = contrib
projects[] = pathauto
projects[pathauto][subdir] = contrib
projects[] = strongarm
projects[strongarm][subdir] = contrib
projects[] = token
projects[token][subdir] = contrib
projects[] = views
projects[views][subdir] = contrib
projects[] = rules
projects[rules][subdir] = contrib



;Administration
projects[] = admin_menu
projects[admin_menu][subdir] = contrib
projects[] = module_filter
projects[module_filter][subdir] = contrib

;Wysiwyg editor
projects[] =  ckeditor
projects[ckeditor][subdir] = contrib

;include development modules
;includes[dev] = "https://raw.github.com/fadehelix/DrupalDevelopmentScripts/master/drush/dev.make"
