; This file was auto-generated by drush make
core = 7.x

api = 2
;Download drupal core
projects[] = drupal

; Modules
projects[] = advanced_help
projects[] = context
projects[] = ctools
projects[] = entity
projects[] = pathauto
projects[] = token
projects[] = views
projects[] = rules
projects[] = boxes



;Administration
projects[] = admin_menu
projects[] = module_filter

;Wysiwyg editor
projects[] =  ckeditor
;ckeditor library
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%203.6.2-3%20for%20Drupal/ckeditor_3.6.2-3_for_drupal_7.zip"
libraries[ckeditor][destination] = "libraries/cke"

;include development modules
includes[dev] = "https://raw.github.com/fadehelix/DrupalDevelopmentScripts/master/drush/dev.make"
