; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.15"
projects[drupal][translations][] = pl

; Modules
projects[] = advanced_help
projects[] = context
projects[ctools][version] = "1.0"
projects[] = entity
;projects[] = google_analytics
projects[pathauto][version] = "1.0"
projects[token][version] = "1.0"
projects[views][version] = "3.3"


;Administration
projects[] = admin_menu
projects[] module_filter

;Wysiwyg editor
projects[wysiwyg][version] = "2.1"
projects[imce][version] = "1.5"
projects[imce_wysiwyg] = "1.0"
;ckeditor library
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor%20for%20Drupal/CKEditor%203.6.2-3%20for%20Drupal/ckeditor_3.6.2-3_for_drupal_7.zip"
libraries[ckeditor][destination] = "libraries/cke"

;include development modules
includes[dev] = "https://raw.github.com/fadehelix/DrupalDevelopmentScripts/master/drush/dev.make"
